### ISSUE TITLE
Come up with solution for bulleted lists in services.

### ISSUE THREAD

**Issue by kimmouser** [ChemistryPittsburgh/ecms#57]
http://ecms.chemistry.digital:8080/service/metal-panel-fabrication/

![screen shot 2016-11-28 at 11 48 56 am](https://cloud.githubusercontent.com/assets/16961015/20677317/aeee4df8-b560-11e6-85bf-07e384779afc.png)

![screen shot 2016-11-28 at 11 52 29 am](https://cloud.githubusercontent.com/assets/16961015/20677465/2f7b22a2-b561-11e6-94f8-e04198751ee3.png)

That hanging paragraph should follow the bulleted list. I looked in the CMS and can't seem to fix it from there.

**Comment by jeffbinando** [comment]
This was caused by having the bulleted lists in 2 columns. It was initially in the design to have any lists so it's kind of breaking the design as is and adding in the ability to have multiple columns is making things difficult with the way that the cms is currently set up. To avoid having the floated paragraph i had to remove the multiple columns for lists for the time being.
